services:
  database:
    profiles:
      - prod
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=movies'
      - 'POSTGRES_DB=movies'
      - 'POSTGRES_PASSWORD=password'